'use client';
import { useMemo,useState } from 'react';
import Image from 'next/image';
import { ArrowRight,ImagePlus,PackagePlus,Pencil,X } from 'lucide-react';
import { adminCreateProduct,adminUpdateProduct,type NewProductInput,type StoredProduct } from '../../lib/products';
const allSizes=['S','M','L','XL','XXL'];
const placements=['Front','Back','Left sleeve','Right sleeve','Collar','Custom placement'];
const txt=(d:FormData,n:string)=>String(d.get(n)||'').trim();
const file=(d:FormData,n:string)=>{const v=d.get(n);return v instanceof File&&v.size?v:undefined;};
export default function ProductManager({products,onCreated}:{products:StoredProduct[];onCreated:(p:StoredProduct)=>void}){
 const [editing,setEditing]=useState<StoredProduct|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const nextNumber=useMemo(()=>String(Math.max(0,...products.map(p=>Number(p.number)||0))+1).padStart(2,'0'),[products]);
 async function submit(e:React.SyntheticEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);setMessage('');setError('');try{
  const sizes=allSizes.filter(s=>d.getAll('sizes').includes(s));if(!sizes.length)throw new Error('Choose at least one size.');
  const customizable=d.get('customizable')==='on',customizationPlacements=placements.filter(x=>d.getAll('placements').includes(x));
  if(customizable&&!customizationPlacements.length)throw new Error('Choose at least one customization placement.');
  const base={name:txt(d,'name'),slug:txt(d,'slug').toLowerCase(),price:Number(txt(d,'price')),color:txt(d,'color'),description:txt(d,'description'),printDetails:txt(d,'print_details'),number:txt(d,'number'),sortOrder:Number(txt(d,'sort_order')),sizes,status:(d.get('published')==='on'?'published':'draft') as 'published'|'draft',customizable,customizationPlacements};
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(base.slug))throw new Error('The URL slug can use lowercase letters, numbers and hyphens only.');
  let saved:StoredProduct;if(editing)saved=await adminUpdateProduct(editing.id,{...base,front:file(d,'front'),back:file(d,'back'),model:file(d,'model')});else{const front=file(d,'front'),back=file(d,'back'),model=file(d,'model');if(!front||!back||!model)throw new Error('Add all three product images.');saved=await adminCreateProduct({...base,front,back,model} as NewProductInput);}
  onCreated(saved);setMessage(`${saved.name} was ${editing?'updated':'created'}.`);setEditing(null);form.reset();
 }catch(c){setError(c instanceof Error?c.message:'Could not save the product.');}finally{setBusy(false);}}
 const p=editing;return <div className="admin-products-layout"><section className="admin-product-form-panel"><div className="admin-section-title"><span><PackagePlus size={18}/>{p?'EDIT PRODUCT':'NEW PRODUCT'}</span><h2>{p?'Refine the product.':'Build the next drop.'}</h2><p>Edit every detail, image, offered size and customization option.</p></div>
 {message&&<output className="system-notice success">{message}</output>}{error&&<div className="system-notice error" role="alert">{error}</div>}
 <form key={p?.id||'new'} className="admin-product-form" onSubmit={submit}><fieldset><legend><span>01</span> Product identity</legend><div className="admin-form-grid">
 <label className="admin-field-wide">Product name<input name="name" required defaultValue={p?.name}/></label><label>URL slug<input name="slug" required defaultValue={p?.slug}/></label><label>Drop number<input name="number" required defaultValue={p?.number||nextNumber}/></label><label>Price (MAD)<input name="price" type="number" min="1" required defaultValue={p?.price}/></label><label>Garment color<input name="color" required defaultValue={p?.color}/></label><label>Display order<input name="sort_order" type="number" min="0" required defaultValue={p?.sortOrder??products.length*10+10}/></label></div></fieldset>
 <fieldset><legend><span>02</span> Story & options</legend><label>Product description<textarea name="description" required minLength={10} maxLength={1000} rows={5} defaultValue={p?.description}/></label><label>Print details<input name="print_details" required defaultValue={p?.printDetails||'Front & back printed'}/></label>
 <div className="admin-size-picker"><span>Offered sizes</span><div>{allSizes.map(s=><label key={s}><input type="checkbox" name="sizes" value={s} defaultChecked={p?p.sizes.includes(s):true}/><span>{s}</span></label>)}</div></div>
 <label className="admin-publish-toggle admin-customizable-toggle"><input type="checkbox" name="customizable" defaultChecked={p?.customizable}/><span><strong>Customizable design</strong><small>Unlock the customer design brief, placement picker and private artwork upload.</small></span></label>
 <div className="admin-size-picker"><span>Allowed placements</span><div>{placements.map(x=><label key={x}><input type="checkbox" name="placements" value={x} defaultChecked={p?.customizationPlacements?.includes(x)??['Front','Back','Left sleeve','Right sleeve'].includes(x)}/><span>{x}</span></label>)}</div></div></fieldset>
 <fieldset><legend><span>03</span> Product photography</legend><p className="admin-field-help">JPG, PNG or WebP, max 6 MB. {p?'Leave empty to keep the current image.':'All three are required.'}</p><div className="admin-upload-grid">{[['front','Front view'],['back','Back view'],['model','Collection card']].map(([n,t])=><label className="admin-upload" key={n}><ImagePlus size={22}/><strong>{t}</strong><input name={n} type="file" accept="image/jpeg,image/png,image/webp"/></label>)}</div></fieldset>
 <div className="admin-publish-row"><label className="admin-publish-toggle"><input type="checkbox" name="published" defaultChecked={p?.status==='published'}/><span><strong>Published</strong><small>Turn off to keep as draft.</small></span></label>{p&&<button type="button" className="secondary" onClick={()=>setEditing(null)}><X size={16}/>Cancel</button>}<button className="primary" disabled={busy}>{busy?'Saving…':p?'Save changes':'Create product'} <ArrowRight size={17}/></button></div></form></section>
 <aside className="admin-catalog-panel"><div className="admin-section-title compact"><span>CATALOG · {products.length} PRODUCTS</span><h2>Current lineup.</h2></div><div className="admin-product-list">{products.map(product=><article key={product.id}><Image src={product.model} alt="" width={66} height={76} unoptimized/><div><small>DROP {product.number} · {product.status}{product.customizable?' · CUSTOM':''}</small><strong>{product.name}</strong><span>{product.color} · {product.sizes.join(' / ')}</span></div><b>{product.price} MAD</b><button type="button" aria-label={`Edit ${product.name}`} onClick={()=>{setEditing(product);setMessage('');setError('');window.scrollTo({top:0,behavior:'smooth'});}}><Pencil size={16}/></button></article>)}</div></aside></div>;
}
