create table if not exists public.store_signup_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text,
  email_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists store_signup_attempts_created_at_idx
  on public.store_signup_attempts(created_at desc);
create index if not exists store_signup_attempts_ip_hash_idx
  on public.store_signup_attempts(ip_hash, created_at desc);
create index if not exists store_signup_attempts_email_hash_idx
  on public.store_signup_attempts(email_hash, created_at desc);

alter table public.store_signup_attempts enable row level security;
revoke all on table public.store_signup_attempts from public, anon, authenticated;
